### ISSUE TITLE
Post-Training-Quantization

### ISSUE THREAD

**Issue by saivinaypsv** [brentspell/hifi-gan-bwe#3]
I trained blow attached algorithm and verifed performance with & without POST-TRAINING-QUNATIZATION .
_[HiFi-GAN: High Fidelity Denoising and Dereverberation Based on Speech Deep Features in Adversarial Networks](https://arxiv.org/pdf/2006.05694)._

Any update on Post-Training-Quantization model  for [Bandwidth Extension is All You Need]?

**Comment by brentspell** [comment]
The paper doesn't have any notes about model quantization, and I have not done any of my own experiments with quantization. Given the similarity of the non-causal wavenet architectures between the two papers, you would probably have similar success with quantization in HiFi-GAN+.
