### ISSUE TITLE
audio data frame size in inference time

### ISSUE THREAD

**Issue by saivinaypsv** [brentspell/hifi-gan-bwe#4]
In current implementation inference-time entire audio data proceesing at a time for recunstructing high quality signal.

Modified the processing logic  & Observed performance degradation with processing frame by frame in infence time.

any suggestion is highly appreciated.

**Comment by brentspell** [comment]
That's interesting, I'm guessing that processing the audio on short frames (~0.025ms, 1200 samples) will have problems with the large receptive field (~13000 samples) in this wavenet model. You might have some success with a much larger frame size (at least the size of the receptive field) using cross-fading, but I wouldn't expect it to sound better than processing the whole audio clip at once.

If you're looking to process smaller chunks of audio for streaming purposes, you might be interested in this [blog post](https://andrew.gibiansky.com/streaming-audio-synthesis/). It describes a technique for streaming convolutions, which can be adapted to wavenet-style models.

**Comment by saivinaypsv** [comment]
Hello Brentspell/Hifi-Gan-Bwe,

I went through this link  Streaming Audio Synthesis (gibiansky.com)
<https://andrew.gibiansky.com/streaming-audio-synthesis/> ,  I didn't get
much idea how to process short segments.

My receptive field of the netwerk ( kernel_size - 1 ) *
stacks*sum(dilation for all layers)   => (3-1)*2*1023 => 4092.

I want to run my BWE setup in real time with a shorter frame size of
10/16/20 and hop sizes . Is it possible to generate better outputs?

**Comment by brentspell** [comment]
Yeah, it sounds like using a windowed/overlap-and-add approach with cross-fading didn't work well for you. I think the only thing that will work will be an exact streaming implementation as described in the Gibiansky blog post.

**Comment by saivinaypsv** [comment]
Brent,

I have successfully implemented frame-wise processing the wavenet by
maintaining the history/past frame data for real-time testing, also It is
exactly matching the outputs by processing with the entire audio file.

But wavenet CPU consumption is more because of this. I did some
customization in wavenet architecture for the light-weight (low-complexity
) version by modifying the wavent-channels and introducing groups in
dilated Convolution. But unfortunately I observed some disturbance in
the HR reconstructed signal.

 Do we have any light-weight version of wavent model that can be run in
realtime setup with less cpu usage without much degradation in
reconstructed signal ?

Looking forward to hearing from you.🙂

Regards,
Sai.

**Comment by brentspell** [comment]
Unfortunately, I don't know of any lightweight wavenet models for bandwidth extension that can be run in real-time on CPU. It might be possible to adapt something like [HiFi-GAN](https://github.com/jik876/hifi-gan) or [UnivNet](https://github.com/mindslab-ai/univnet) to the bandwidth extension task, but I haven't heard of anyone doing so. The [HiFi++](https://arxiv.org/abs/2203.13086) paper is also a promising approach, but I haven't spent any time with it.

**Comment by saivinaypsv** [comment]
Hello Brent,

Why is Noise Sequence used in the UnivNet network?

**Comment by brentspell** [comment]
I believe the use of noise vector inputs goes back to some of the original GAN-based image generators. However, the theory behind the noise inputs probably goes back to VAE models, which use Gaussian noise as a prior distribution for sampling. In terms of vocoders, I recall [Parallel-WaveGAN](https://arxiv.org/abs/1910.11480) using noise inputs, but the [MelGAN](https://arxiv.org/abs/1910.06711) and [HiFi-GAN](https://arxiv.org/abs/2010.05646) vocoders do not. The MelGAN paper provides some justification for this, citing some GAN-based image and video models that don't use noise inputs.
