### ISSUE TITLE
Very high CPU and memory usage whth hifi-synth

### ISSUE THREAD

**Issue by Baiyuetribe** [brentspell/hifi-gan-bwe#5]
![image](https://user-images.githubusercontent.com/43716063/171902599-50de47cc-0656-4cc0-8e0c-1200acb5bcea.png)
```bash
hifi-synth hifi-gan-bwe-10-42890e3-vctk-48kHz input.mp3 output.wav
```
Can I enable GPU acceleration if the running memory and CPU consumption are too much?

**Comment by brentspell** [comment]
Yes, if you have a CUDA-enabled GPU, you can enable it by loading the model and data onto the GPU before running inference.

https://github.com/brentspell/hifi-gan-bwe/blob/584f28697b69eb7bec51eb2bd5a3d3b7bba79495/hifi_gan_bwe/scripts/synth.py#L42
```python
model = models.BandwidthExtender.from_pretrained(args.model).cuda()
```

https://github.com/brentspell/hifi-gan-bwe/blob/584f28697b69eb7bec51eb2bd5a3d3b7bba79495/hifi_gan_bwe/scripts/synth.py#L55
```python
audio = np.stack([model(torch.from_numpy(x).cuda(), sample_rate).cpu() for x in audio.T]).T
```

**Comment by brentspell** [comment]
This would also be a useful feature to have in the library, so I'll look into adding it to the script.

**Comment by brentspell** [comment]
This has been released in version 0.1.13 of the library. You can modify your command above as follows to run synthesis on a CUDA-capable GPU:

```
hifi-synth --device=cuda hifi-gan-bwe-10-42890e3-vctk-48kHz input.mp3 output.wav
```

Please reopen the issue if you run into any problems with this change.

**Comment by Baiyuetribe** [comment]
cuda takes effect, but the gpu memory overflows. The source file audio is only 4M.
![image](https://user-images.githubusercontent.com/43716063/171971532-c37d4518-3976-463b-aa27-a2d268020642.png)

**Comment by Baiyuetribe** [comment]
Also I can't reopen the issue, you seem to have disabled it
![image](https://user-images.githubusercontent.com/43716063/171971630-a89e4091-8bd2-4c20-91fe-f84837ebb4f0.png)

**Comment by brentspell** [comment]
Ah yes, an 11MB MP3 file would be quite a bit of audio, which explains the OOM on the GPU. It would be nice if the synth script would break up the audio into segments, process them, and then reassemble the resulting audio. If I get some time this week, I'll add that to the script.

**Comment by brentspell** [comment]
I added streaming/cross-fading support in the `hifi-synth` script to version 0.1.14 of the library. By default, the script will window the signal into 30sec frames with 25ms cross-fading overlap, but these can be customized when you call the script. Thanks again for the report, and I hope this helps.
