### ISSUE TITLE
Performance Evalution Metric

### ISSUE THREAD

**Issue by saivinaypsv** [brentspell/hifi-gan-bwe#6]
Hi brentspell,

What is the PERFECT/BEST evaluation metric for BWE ? POLQA can be used for BWE evalution metric or not?

**Comment by brentspell** [comment]
If you take a look at the original [paper](https://ieeexplore.ieee.org/document/9413575), the authors use Peak Signal-to-Noise Ratio (PSNR) and Log-Spectral Distance (LSD) as objective evaluation metrics. However, they note that these aren't great indicators of perceptual quality, so they collect Mean Opinion Scores (MOS) using Amazon Mechanical Turk. I haven't done any of these evaluations myself.

I have had some success in the past with the [PESQ](https://github.com/ludlows/PESQ) evaluation metric for vocoders. However, using it requires downsampling to 16kHz, which probably won't work well for bandwidth extension.
