### ISSUE TITLE
Discriminator Output Projection Dimension

### ISSUE THREAD

**Issue by taucontrib** [brentspell/hifi-gan-bwe#7]
https://github.com/brentspell/hifi-gan-bwe/blob/6fd6323dde721fa4a4fc81b69a341a4ae74682d5/hifi_gan_bwe/models.py#L334

The discriminator in this repo projects every input audio to a float in the interval [0,1] via `x = x.mean(dim=-1)` while the original paper suggests window based discriminators (if i got it right), not only for the feature matching loss as done in this repo. Any hints why this design choice has been made? 

Another question: have you tried to use 1m instead of 100k warmup steps before applying adversarial training as proposed in the paper? 

Thank you for the great implementation!

**Comment by brentspell** [comment]
Hi taucontrib,

I don't see a reference to window-based discriminators in the paper. As far as I can tell, the discriminator losses are supposed to be computed over all audio samples in the batch, both for feature matching and for the discriminator loss. Do you know where in the paper you saw the reference to window-based discriminators?

The `WaveDiscriminator` that you link to at that line number doesn't project the audio to [0, 1]. Its final layer is a linear projection, although this discriminator is trained in the LS-GAN framework against a real/fake (1/0) target.

I haven't tried warming up the generator to 1M steps, but that would be an interesting experiment. The generator loss curve seem to be somewhat converged after 100k with the VCTK dataset, but there might be some benefit to warming up for longer.

Thanks for the feedback!

**Comment by taucontrib** [comment]
Thanks for the quick response! 
I thought the window based discriminators we're being used because the paper reads
_"we use a set of waveform discriminators [...] following the design in MelGAN"_

You're right ofc, it's not limited to [0,1] - my bad.

**Comment by brentspell** [comment]
Ah, I did not catch that in my initial read. I think windowed discriminators are usually just used to reduce GPU memory usage, but it could be worth an experiment. The receptive field of this discriminator isn't that large, but the extra smoothing caused by averaging again over windowed audio might reduce the variance of the gradients.

**Comment by taucontrib** [comment]
Thanks for the help! Will close the issue:)
