### ISSUE TITLE
Configs for other than 22050 Hz data

### ISSUE THREAD

**Issue by asarsembayev** [brentspell/hifi-gan-bwe#8]
Hi! Thank you for your work!
Can you please show your configs for training 8KHz data?
Like this [one](https://github.com/jik876/hifi-gan/blob/master/config_v1.json)

**Comment by brentspell** [comment]
Hello Aidos. If you want to train a model to upsample only from 8kHz to 48kHz, you can change the list on [this line](https://github.com/brentspell/hifi-gan-bwe/blob/6fd6323dde721fa4a4fc81b69a341a4ae74682d5/hifi_gan_bwe/datasets.py#L41) to include only the value 8000.
